# -*- mode: python ; coding: utf-8 -*-
# Atlas Quant Platform - Desktop Executable Spec
# 打包 Atlas.exe（PySide6 桌面客户端，含真实历史数据 + engine v2 模块）

a = Analysis(
    ['..\\desktop\\main.py'],
    # 加入项目根，使 desktop 能 import engine（data_center_v2/evaluation_v2/export）
    pathex=['..\\desktop', '..'],
    binaries=[],
    datas=[
        # 真实历史数据（520 期大乐透）+ 样例回退
        ('..\\data\\raw\\dlt_history.csv', 'data\\raw'),
        ('..\\data\\raw\\dlt_2024_sample.csv', 'data\\raw'),
        ('..\\data\\raw\\ssq_2024_sample.csv', 'data\\raw'),
        ('..\\branding\\logo.ico', 'branding'),
    ],
    hiddenimports=[
        'matplotlib.backends.backend_qtagg',
        'matplotlib.backends.backend_qt5agg',
        'fpdf',
        'engine.data_center_v2',
        'engine.data_center_v2.sources',
        'engine.data_center_v2.quality',
        'engine.data_center_v2.models',
        'engine.evaluation_v2',
        'engine.evaluation_v2.split',
        'engine.evaluation_v2.baseline',
        'engine.evaluation_v2.metrics',
        'engine.evaluation_v2.disclaimer',
        'engine.export',
        'engine.export.markdown',
        'engine.export.csv',
        'engine.export.png',
        'engine.export.pdf',
        'engine.beta',
        'engine.beta.manager',
        'engine.product_analytics_v2',
        'engine.product_analytics_v2.analytics',
        'backend.feedback',
        'backend.feedback.models',
        'backend.feedback.service',
        'release_center',
        'release_center.release',
        'engine.user_intelligence.v3',
        'engine.user_intelligence.v3.events',
        'engine.value_score',
        'engine.value_score.score',
        'engine.product_value',
        'engine.product_value.value',
        'backend.subscription.v2',
        'backend.subscription.v2.plans',
        'engine.feedback_intelligence',
        'engine.feedback_intelligence.intel',
        'engine.intelligence.product_director_v2',
        'engine.lottery_intent',
        'engine.lottery_intent.intent_router',
        'engine.lottery_intent.ticket_parser',
        'engine.lottery_intent.draw_matcher',
        'engine.lottery_intent.prize_calculator',
        'engine.assistant',
        'engine.assistant.registry',
        'engine.assistant.router',
        'engine.ticket_system',
        'engine.ticket_system.manager',
        'engine.ticket_system.date_parser',
        'engine.ticket_system.schedule',
        'engine.task_context',
        'engine.task_context.manager',
        'engine.lottery_quant',
        'engine.lottery_quant.probability',
        'engine.lottery_quant.structure',
        'engine.lottery_quant.simulation',
        'engine.lottery_quant.risk',
        'engine.lottery_quant.portfolio',
        'engine.lottery_quant.backtest',
        'engine.lottery_quant.report',
        'engine.lottery_quant.quant_director',
        'engine.user_behavior',
        'engine.user_behavior.behavior',
        'engine.budget_manager',
        'engine.budget_manager.budget',
        'engine.personal_review',
        'engine.personal_review.review',
        'engine.reminder_center',
        'engine.reminder_center.reminder',
        'engine.personal_growth',
        'engine.personal_growth.growth',
        'engine.report_center',
        'engine.report_center.center',
        'engine.chase_analysis',
        'engine.chase_analysis.analysis',
        'engine.user_memory',
        'engine.user_memory.memory',
        # v4.2 数据飞轮模块
        'engine.user_archive',
        'engine.user_archive.archive',
        'engine.auto_review',
        'engine.auto_review.review',
        'engine.growth_health',
        'engine.growth_health.health',
        'engine.annual_report',
        'engine.annual_report.report',
        'engine.premium',
        'engine.premium.plan',
        # v4.3 留存闭环模块
        'engine.user_events',
        'engine.user_events.events',
        'engine.claim_center',
        'engine.claim_center.claim',
        'engine.asset_center',
        'engine.asset_center.asset',
        'engine.growth_system',
        'engine.growth_system.growth',
        # v4.3.1 增量更新器
        'engine.data_center_v2',
        'engine.data_center_v2.sources',
        'engine.data_center_v2.updater',
        'engine.data_center_v2.models',
        'engine.data_center_v2.quality',
        # v4.4 实时开奖
        'engine.live_draw',
        'engine.live_draw.events',
        'engine.live_draw.service',
        'engine.live_draw.background',
        'engine.live_draw.health',
        'engine.live_draw.claim_link',
        # v4.5 数据可信 + 监控 + 提醒 + 埋点
        'engine.data_center',
        'engine.data_center.providers',
        'engine.data_center.validation',
        'engine.data_center.health',
        'engine.draw_monitor',
        'engine.draw_monitor.monitor',
        'engine.draw_monitor.notifier',
        'engine.draw_monitor.reminder_schedule',
        'engine.user_events.report',
        # v4.6 用户运营验证
        'engine.user_analytics',
        'engine.user_analytics.analytics',
        'engine.user_analytics.funnel',
        'engine.user_analytics.retention',
        'engine.asset_center.monthly',
        'engine.premium.feature_test',
        # v4.7 个人彩票行为分析
        'engine.behavior_analysis',
        'engine.behavior_analysis.analysis',
        'engine.behavior_analysis.score',
        'engine.behavior_analysis.weekly',
        'engine.strategy_review',
        'engine.strategy_review.review',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Atlas',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='..\\branding\\logo.ico',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
