"""Atlas Quant Platform - Report Engine.

报告引擎基于分析结果生成结构化报告。
支持 Markdown, CSV, JSON 格式。
所有函数为纯计算: 无IO、无数据库。
"""
from __future__ import annotations

import csv
import io
import json
from datetime import datetime
from typing import Any, Dict, List, Optional

from engine.backtest.models import TradeRecord, BacktestMetrics, BacktestConfig


class ReportGenerator:
    """报告生成器 - 消费Engine输出, 生成结构化报告。"""

    def __init__(self) -> None:
        self._sections: List[Dict[str, Any]] = []
        self._title: str = "Analysis Report"
        self._created_at: str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def set_title(self, title: str) -> None:
        self._title = title

    def add_section(self, title: str, content: Any, chart: Optional[str] = None) -> None:
        self._sections.append({"title": title, "content": content, "chart": chart})

    def _disclaimer(self) -> str:
        return (
            "\n\n---\n\n"
            "*Generated by Atlas Quant Platform.*  "
            "*This report is for academic research purposes only. "
            "Does not predict lottery outcomes.*"
        )

    def generate_markdown(self, engine_result: Dict[str, Any]) -> str:
        """从引擎输出生成结构化Markdown报告。"""
        analysis_type = engine_result.get("analysis_type", "analysis")
        lines: List[str] = [
            f"# {self._title}",
            "",
            f"*Generated: {self._created_at}*",
            "",
            f"**Analysis Type**: {analysis_type}",
            "",
        ]

        total_draws = engine_result.get("total_draws", 0)
        lines.append(f"**Total Draws Analyzed**: {total_draws}")
        lines.append("")

        if "main_numbers" in engine_result:
            main = engine_result["main_numbers"]
            if isinstance(main, dict) and "range" in main:
                r = main["range"]
                lines.append(f"## Main Numbers (Range: {r['min']}-{r['max']}, Size: {r['size']})")
                lines.append("")
                if "frequencies" in main:
                    lines.extend(self._format_frequency_section(main))
                if "current_max_gap" in main:
                    lines.extend(self._format_gap_section(main))
                if "hot_numbers" in main:
                    lines.append("### Hot Numbers (Most Frequent)")
                    lines.append("")
                    for item in main.get("hot_numbers", []):
                        lines.append(f"- Number **{item['number']}**: {item['count']} times")
                    lines.append("")
                if "cold_numbers" in main:
                    lines.append("### Cold Numbers (Least Frequent)")
                    lines.append("")
                    for item in main.get("cold_numbers", []):
                        lines.append(f"- Number **{item['number']}**: {item['count']} times")
                    lines.append("")
            if "top_missing" in main:
                lines.append("### Top Missing Numbers (Longest Current Gap)")
                lines.append("")
                lines.append("| Number | Current Gap | Avg Gap | Max Gap |")
                lines.append("|--------|-------------|---------|---------|")
                for item in main.get("top_missing", []):
                    avg = item.get("average_gap", "N/A")
                    lines.append(f"| {item['number']} | {item['current_gap']} | {avg} | {item['max_gap']} |")
                lines.append("")

        if "bonus_numbers" in engine_result and engine_result["bonus_numbers"]:
            bonus = engine_result["bonus_numbers"]
            if isinstance(bonus, dict) and "range" in bonus:
                r = bonus["range"]
                lines.append(f"## Bonus Numbers (Range: {r['min']}-{r['max']}, Size: {r['size']})")
                lines.append("")

        if "odd_even" in engine_result:
            oe = engine_result["odd_even"]
            lines.append("## Odd/Even Distribution")
            lines.append("")
            lines.append("| Ratio | Count | % |")
            lines.append("|-------|-------|---|")
            dist = oe.get("distribution", {})
            pct = oe.get("percentages", {})
            for ratio, count in dist.items():
                lines.append(f"| {ratio} | {count} | {pct.get(ratio, 0)}% |")
            lines.append(f"\n**Current**: {oe.get('current', 'N/A')}")
            lines.append("")

        if "high_low" in engine_result:
            hl = engine_result["high_low"]
            lines.append("## High/Low Distribution")
            lines.append("")
            lines.append(f"Midpoint: {hl.get('midpoint', 'N/A')}")
            lines.append("| Ratio | Count | % |")
            lines.append("|-------|-------|---|")
            dist = hl.get("distribution", {})
            pct = hl.get("percentages", {})
            for ratio, count in dist.items():
                lines.append(f"| {ratio} | {count} | {pct.get(ratio, 0)}% |")
            lines.append("")

        if "chi_square" in engine_result.get("main_numbers", {}):
            cs = engine_result["main_numbers"]["chi_square"]
            if cs:
                lines.append("## Chi-Square Test")
                lines.append(f"- **Statistic**: {cs.get('statistic', 'N/A')}")
                lines.append(f"- **P-Value**: {cs.get('p_value', 'N/A')}")
                lines.append(f"- **Significant (p<0.05)**: {cs.get('significant', 'N/A')}")
                lines.append("")

        # Monte Carlo / Entropy / simulation sections
        if "num_simulations" in engine_result:
            lines.append("## Monte Carlo Simulation")
            lines.append(f"- **Simulations**: {engine_result.get('num_simulations', 0)}")
            lines.append(f"- **Total combinations**: {engine_result.get('total_combinations_generated', 0)}")
            lines.append("")

        if "entropy" in engine_result.get("main_numbers", {}):
            ent = engine_result["main_numbers"]["entropy"]
            lines.append("## Entropy Analysis")
            lines.append(f"- **Shannon Entropy**: {ent.get('shannon_entropy', 'N/A')}")
            lines.append(f"- **Uniformity**: {ent.get('uniformity_pct', 'N/A')}%")
            lines.append("")

        lines.append(self._disclaimer())
        return "\n".join(lines)

    def generate_backtest_report(
        self,
        metrics: BacktestMetrics,
        trades: List[TradeRecord],
        config: Optional[BacktestConfig] = None,
    ) -> str:
        """Generate a Markdown backtest report from metrics and trades.

        Args:
            metrics: BacktestMetrics from ResultAggregator.
            trades: List of TradeRecord from TradeSimulator.
            config: BacktestConfig used for the run.

        Returns:
            Markdown report string.
        """
        lines: List[str] = [
            f"# Backtest Report: {self._title}",
            "",
            f"*Generated: {self._created_at}*",
            "",
            "## Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total Bets | {metrics.total_bets} |",
            f"| Win Count | {metrics.win_count} |",
            f"| Win Rate | {metrics.win_rate:.2f}% |",
            f"| Total Investment | ${metrics.total_investment:.2f} |",
            f"| Total Return | ${metrics.total_return:.2f} |",
            f"| ROI | {metrics.roi:.2f}% |",
            f"| Final Capital | ${metrics.final_capital:.2f} |",
            f"| Max Drawdown | ${metrics.max_drawdown_amount:.2f} ({metrics.max_drawdown_pct:.2f}%) |",
            f"| Volatility | {metrics.volatility:.4f} |",
            f"| Sharpe Ratio | {metrics.sharpe_ratio:.4f} |",
            f"| Avg Return per Bet | ${metrics.avg_return_per_bet:.2f} |",
            f"| Best Single Return | ${metrics.best_single_return:.2f} |",
            f"| Worst Single Return | ${metrics.worst_single_return:.2f} |",
            f"| Max Consecutive Losses | {metrics.max_consecutive_losses} |",
            "",
        ]

        if config:
            lines.append("## Configuration")
            lines.append("")
            lines.append(f"| Parameter | Value |")
            lines.append(f"|-----------|-------|")
            lines.append(f"| Lottery | {config.lottery_code} |")
            lines.append(f"| Strategy | {config.strategy_id} |")
            lines.append(f"| Date Range | {config.start_date} - {config.end_date} |")
            lines.append(f"| Initial Capital | ${config.initial_capital:.0f} |")
            lines.append(f"| Bet per Draw | ${config.bet_per_draw:.0f} |")
            lines.append("")

        if metrics.prize_levels:
            lines.append("## Prize Level Distribution")
            lines.append("")
            lines.append("| Level | Count |")
            lines.append("|-------|-------|")
            for lvl in sorted(metrics.prize_levels.keys(), key=int):
                lines.append(f"| {lvl} | {metrics.prize_levels[lvl]} |")
            lines.append("")

        lines.append("## Recent Trades (Last 20)")
        lines.append("")
        lines.append("| Date | Draw | Bet | Win | PnL | Result | Prize |")
        lines.append("|------|------|-----|-----|-----|--------|-------|")
        recent = trades[-20:] if len(trades) > 20 else trades
        for t in recent:
            pnl = t.win_amount - t.bet_amount
            result = "WIN" if t.is_win else "LOSS"
            prize = str(t.prize_level) if t.prize_level > 0 else "-"
            lines.append(f"| {t.draw_date} | {t.draw_number} | ${t.bet_amount:.0f} | "
                         f"${t.win_amount:.0f} | ${pnl:.0f} | {result} | {prize} |")
        lines.append("")

        if trades:
            lines.append("## Performance Curve")
            lines.append("")
            lines.append("```")
            dates = [t.draw_date for t in trades[::max(1, len(trades)//10)]]
            pnls = [t.cumulative_pnl for t in trades[::max(1, len(trades)//10)]]
            for d, p in zip(dates, pnls):
                bar_len = max(1, int(abs(p) / 10))
                bar = "█" * bar_len if p >= 0 else "░" * bar_len
                lines.append(f"{d} {bar} ${p:.0f}")
            lines.append("```")
            lines.append("")

        lines.append(self._disclaimer())
        return "\n".join(lines)

    def _format_frequency_section(self, data: Dict[str, Any]) -> List[str]:
        lines: List[str] = []
        expected = data.get("expected_per_number", 0)
        lines.append(f"**Expected frequency per number**: {expected}")
        lines.append("")
        lines.append("| Number | Frequency | vs Expected |")
        lines.append("|--------|-----------|-------------|")
        sorted_items = sorted(data.get("frequencies", {}).items(), key=lambda x: x[1], reverse=True)[:15]
        for num_str, count in sorted_items:
            diff = count - expected
            sign = "+" if diff > 0 else ""
            lines.append(f"| {num_str} | {count} | {sign}{round(diff, 1)} |")
        lines.append("")
        return lines

    def _format_gap_section(self, data: Dict[str, Any]) -> List[str]:
        return [
            f"**Current Max Gap**: {data.get('current_max_gap', 'N/A')}",
            f"**Current Avg Gap**: {data.get('current_avg_gap', 'N/A')}",
            f"**Overall Max Gap**: {data.get('overall_max_gap', 'N/A')}",
            "",
        ]

    def generate_csv(self, data: List[Dict[str, Any]]) -> str:
        output = io.StringIO()
        if data:
            writer = csv.DictWriter(output, fieldnames=data[0].keys())
            writer.writeheader()
            writer.writerows(data)
        return output.getvalue()

    def generate_json(self, data: Any) -> str:
        return json.dumps(data, ensure_ascii=False, indent=2, default=str)
